name: elevenlabs_flutter_app
description: A Flutter app for ElevenLabs conversational AI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # WebSocket and HTTP support
  web_socket_channel: ^2.4.0
  http: ^1.1.0
  
  # JSON handling
  json_annotation: ^4.8.1
  
  # State management
  provider: ^6.1.1
  
  # Audio playback
  just_audio: ^0.9.34
  
  # Speech recognition
  speech_to_text: ^6.6.0
  permission_handler: ^11.0.1
  
  # UI components
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true